spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta_logistics_order
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 19099
