server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth
          predicates:
            - Path=/**

        - id: hub-service
          uri: lb://hub
          predicates:
            - Path=/**

        - id: company-service
          uri: lb://company
          predicates:
            - Path=/**

        - id: order-service
          uri: lb://order
          predicates:
            - Path=/**

        - id: product-service
          uri: lb://product
          predicates:
            - Path=/**

        - id: delivery-service
          uri: lb://delivery
          predicates:
            - Path=/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


service:
  jwt:
    secret-key: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNwYXJ0YS1ib290Y2FtcC1jaDItc3BhcnRhLWxvZ2lzdGljcy1tYWRlLWJ5LWphYmJlcndvY2tlcjA0