spring:
  application:
    name: ai-service
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

# http://localhost:19097/actuator/refresh 사용을 위한 설정
# 코드 내 @RefreshScope 적용 필요
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/