spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta_logistics_auth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
  # http://localhost:{포트 번호}/actuator/refresh 사용을 위한 설정
  # 코드 내 @RefreshScope 적용 필요
  endpoints:
    web:
      exposure:
        include: refresh
service:
  jwt:
    access-expiration: 3600000
    secret-key: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNwYXJ0YS1ib290Y2FtcC1jaDItc3BhcnRhLWxvZ2lzdGljcy1tYWRlLWJ5LWphYmJlcndvY2tlcjA0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
