spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta_logistics_delivery
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 19098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/