spring:
  application:
    name: hub-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta_logistics_hub
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 19094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
