spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta_logistics_order
    username: postgres
    password: sky2002369
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 19096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/