spring:
  application:
    name: product-service
  data:
    redis:
      host: localhost
      port: 6379
      password: systempass
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta_logistics_product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 19097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
service:
  header:
    id: userId
    username: username
    role : role

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
